package com.example.prakmobilemodul4

class Datasource {
    fun loadList1(): List<DigitalDrawingTool> {
        return listOf<DigitalDrawingTool>(
            DigitalDrawingTool(
                R.string.pentab1_judul,
                R.string.pentab1_harga,
                R.string.pentab1_detail,
                R.drawable.pentab1
            ),
            DigitalDrawingTool(
                R.string.pentab2_judul,
                R.string.pentab2_harga,
                R.string.pentab2_detail,
                R.drawable.pentab2
            ),
            DigitalDrawingTool(
                R.string.pentab3_judul,
                R.string.pentab3_harga,
                R.string.pentab3_detail,
                R.drawable.pentab3
            ),
            DigitalDrawingTool(
                R.string.pentab4_judul,
                R.string.pentab4_harga,
                R.string.pentab4_detail,
                R.drawable.pentab4
            ),
            DigitalDrawingTool(
                R.string.pentab5_judul,
                R.string.pentab5_harga,
                R.string.pentab5_detail,
                R.drawable.pentab5
            ),
            DigitalDrawingTool(
                R.string.pentab6_judul,
                R.string.pentab6_harga,
                R.string.pentab6_detail,
                R.drawable.pentab6
            ),
            DigitalDrawingTool(
                R.string.pentab7_judul,
                R.string.pentab7_harga,
                R.string.pentab7_detail,
                R.drawable.pentab7
            ),
            DigitalDrawingTool(
                R.string.pentab8_judul,
                R.string.pentab8_harga,
                R.string.pentab8_detail,
                R.drawable.pentab8
            ),
            DigitalDrawingTool(
                R.string.pentab9_judul,
                R.string.pentab9_harga,
                R.string.pentab9_detail,
                R.drawable.pentab9
            ),
            DigitalDrawingTool(
                R.string.pentab10_judul,
                R.string.pentab10_harga,
                R.string.pentab10_detail,
                R.drawable.pentab10
            )
        )
    }

    fun loadList2(): List<DigitalDrawingTool> {
        return listOf<DigitalDrawingTool>(
            DigitalDrawingTool(
                R.string.display1_judul,
                R.string.display1_harga,
                R.string.display1_detail,
                R.drawable.display1
            ),
            DigitalDrawingTool(
                R.string.display2_judul,
                R.string.display2_harga,
                R.string.display2_detail,
                R.drawable.display2
            ),
            DigitalDrawingTool(
                R.string.display3_judul,
                R.string.display3_harga,
                R.string.display3_detail,
                R.drawable.display3
            ),
            DigitalDrawingTool(
                R.string.display4_judul,
                R.string.display4_harga,
                R.string.display4_detail,
                R.drawable.display4
            ),
            DigitalDrawingTool(
                R.string.display5_judul,
                R.string.display5_harga,
                R.string.display5_detail,
                R.drawable.display5
            ),
            DigitalDrawingTool(
                R.string.display6_judul,
                R.string.display6_harga,
                R.string.display6_detail,
                R.drawable.display6
            ),
            DigitalDrawingTool(
                R.string.display7_judul,
                R.string.display7_harga,
                R.string.display7_detail,
                R.drawable.display7
            ),
            DigitalDrawingTool(
                R.string.display8_judul,
                R.string.display8_harga,
                R.string.display8_detail,
                R.drawable.display8
            ),
            DigitalDrawingTool(
                R.string.display9_judul,
                R.string.display9_harga,
                R.string.display9_detail,
                R.drawable.display9
            )
        )
    }

    fun loadList3(): List<DigitalDrawingTool> {
        return listOf<DigitalDrawingTool>(
            DigitalDrawingTool(
                R.string.tablet1_judul,
                R.string.tablet1_harga,
                R.string.tablet1_detail,
                R.drawable.tablet1
            ),
            DigitalDrawingTool(
                R.string.tablet2_judul,
                R.string.tablet2_harga,
                R.string.tablet2_detail,
                R.drawable.tablet2
            ),
            DigitalDrawingTool(
                R.string.tablet3_judul,
                R.string.tablet3_harga,
                R.string.tablet3_detail,
                R.drawable.tablet3
            ),
            DigitalDrawingTool(
                R.string.tablet4_judul,
                R.string.tablet4_harga,
                R.string.tablet4_detail,
                R.drawable.tablet4
            ),
            DigitalDrawingTool(
                R.string.tablet5_judul,
                R.string.tablet5_harga,
                R.string.tablet5_detail,
                R.drawable.tablet5
            ),
            DigitalDrawingTool(
                R.string.tablet6_judul,
                R.string.tablet6_harga,
                R.string.tablet6_detail,
                R.drawable.tablet6
            ),
            DigitalDrawingTool(
                R.string.tablet7_judul,
                R.string.tablet7_harga,
                R.string.tablet7_detail,
                R.drawable.tablet7
            ),
            DigitalDrawingTool(
                R.string.tablet8_judul,
                R.string.tablet8_harga,
                R.string.tablet8_detail,
                R.drawable.tablet8
            ),
            DigitalDrawingTool(
                R.string.tablet9_judul,
                R.string.tablet9_harga,
                R.string.tablet9_detail,
                R.drawable.tablet9
            ),
            DigitalDrawingTool(
                R.string.tablet10_judul,
                R.string.tablet10_harga,
                R.string.tablet10_detail,
                R.drawable.tablet10
            )
        )
    }



}